### ISSUE TITLE
New account confirmation message takes too long to pop up

### ISSUE THREAD

**Issue by Vivi-Vo** [revaturelabs/trackforce#653] opened 2018-08-28 13:48 UTC
Confirmation message did not pop up after registering, but redirect user back to login page then show the message.

**Steps to reproduce**
1. Pull up login home page
2. Click Register button
3. Fill in new user information
4. Click Register New User

**Comment by Quinn-Donnelly** [comment] 2018-08-28 13:50
Duplicate of #647

**Closed by Quinn-Donnelly** 2018-08-28 13:50 UTC
Labels: duplicate
